### ISSUE TITLE
use reflector

### ISSUE THREAD

**Issue by CodigoCristo** [Torxed/archinstall_gui#1]
They could use reflector to update the best mirrors

**Comment by Torxed** [comment]
Adding in the reflector in the `mirrors` step would be a good idea.
Could be used in junction with filtering regions.

**Comment by Torxed** [comment]
Some tweaks have been done in the mirror process.
Among other things, the [https://www.archlinux.org/mirrors/status/json/](https://github.com/Torxed/archinstall_gui/blob/8558e2ca1399c1afc10b787ba83c0af07a3a5ad7/modules/installation_steps/mirrors.py#L123) is now being used to load an active mirror-list.

We then [filter active and https](https://github.com/Torxed/archinstall_gui/blob/8558e2ca1399c1afc10b787ba83c0af07a3a5ad7/modules/installation_steps/mirrors.py#L58-L61) mirrors in order to avoid dead mirrors and "unsafe" mirrors, even tho signature per package is done, it's some how scary to trust HTTP.

Future work will include custom mirrors not listed in the official mirror-list: #11 

Edit: should also mention we use [rankmirrors](https://github.com/Torxed/archinstall/blob/master/archinstall.py#L961) to optimize even a filtered list of mirrors.
